language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    update: true
    packages:
      - cmake 
      - cmake-data
before_script:
  - mkdir build
  - cmake -H. -Bbuild
  - cmake --build build
script:
  - make
  - build/tests/test_B
